name: Docker Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  web:
    name: Build and Publish Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags (lowercase owner for GHCR)
        id: vars
        shell: bash
        run: |
          set -e
          OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${OWNER_LC}/easyappointments-web"
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF_TYPE}" == "branch" && "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "push=true" >> $GITHUB_OUTPUT
            echo "tags=${IMAGE}:latest,${IMAGE}:sha-${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" == v* ]]; then
            echo "push=true" >> $GITHUB_OUTPUT
            echo "tags=${IMAGE}:${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
            echo "tags=${IMAGE}:ci" >> $GITHUB_OUTPUT
          fi

      - name: Build (PR) or Build+Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/apache/Dockerfile.web
          build-args: |
            PHP_VARIANT=8.2
          platforms: linux/amd64,linux/arm64
          push: ${{ steps.vars.outputs.push }}
          tags: ${{ steps.vars.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
